---
name: 'build images'

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Code"
          files: |
            *

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Base Build 
        id: prep_base
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/borgmatic
          TAG="${DOCKER_IMAGE}:latest"

          # Set output parameters.
          echo ::set-output name=tags::${TAG}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Prepare MSMTP Build
        id: prep_msmtp
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/borgmatic
          TAG="${DOCKER_IMAGE}:latest-msmtp"

          # Set output parameters.
          echo ::set-output name=tags::${TAG}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Prepare NTF Build
        id: prep_ntfy
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/borgmatic
          TAG="${DOCKER_IMAGE}:latest-ntfy"

          # Set output parameters.
          echo ::set-output name=tags::${TAG}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build_base
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./base
          file: ./base/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.prep_base.outputs.tags }}

      - name: Build_msmtp
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./msmtp
          file: ./msmtp/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.prep_msmtp.outputs.tags }}

      - name: Build_ntfy
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./ntfy
          file: ./ntfy/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.prep_ntfy.outputs.tags }}